services:
 
  app:
    # Constrói a imagem usando o Dockerfile desta pasta
    build: .
    # Nome do container
    container_name: hospital-sentinela
    # Porta do computador : porta do container
    ports:
      - "3000:3000"
 # Liga o volume à PASTA de dados, não ao arquivo
    volumes:
      - dados_hospital:/app/backend/data
 
# Declara o volume nomeado
volumes:
  dados_hospital:
# Constrói a imagem e sobe o container em segundo plano
docker compose up -d --build
